name: Despliegue en testing

on:
   push:
     branches: [ testing ]

  # workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    environment:
      name: test
    runs-on: ubuntu-latest

    permissions:  
      id-token: write  
      contents: read
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ARN_ROLE_NAME_DEPLOY_TEST }}
          aws-region: ${{secrets.AWS_REGION_TEST}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Workflow
      #  working-directory: aws_s3_bucket
        run: |
          terraform init -backend-config="bucket= ${{ env.BUCKET_NAME_TEST }}" -backend-config="key=state/terraform.tfstate"
      - name: Select Workspace
        run: |
          terraform workspace list
          terraform workspace select test || terraform workspace new test
      - name: Terraform Validate
        run: |
          terraform state pull
          terraform fmt
          terraform validate
      - name: Terraform Plan
        run:  terraform plan
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      - name: Validate Creation/Changes
        run: terraform state list     