name: Terraform Workspaces the real chuperloco

on:
  workflow_dispatch

permissions:
      id-token: write
      contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      environment: dev

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
 
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ARN_ROLE_NAME_DEPLOY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Workflow
      #  working-directory: aws_s3_bucket
        run: |
          terraform init -backend-config="bucket=tarrocaido" -backend-config="key=state/terraform.tfstate"
          terraform workspace new ${{ env.environment }}
          terraform workspace select ${{ env.environment }} && terraform plan
          terraform workspace select ${{ env.environment }} && terraform apply -auto-approve