name: Despliegue en testing

on:
    push:
      branches: [ testing ]

  # workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
    uses: CamiloBaeza/TEST_TERRAFORM_AWS_CBAEZA/.github/workflows/called-workflow.yml@main
    secrets:
      access-token: ${{ secrets.ARN_ROLE_NAME_DEPLOY }}