name: Despliegue en testing

on:
    push:
      branches: [ testing ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      environment: test
    steps:
      - name: deploy
        run: |
             gh api \
             -H "Accept: application/vnd.github+json" \
             /repos/CamiloBaeza/TEST_TERRAFORM_AWS_CBAEZA/actions/secrets
      - name: Get registration token
              id: getRegToken
              run: |
                curl -X POST -H \"Accept: application/vnd.github.v3+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/myprofile/myrepo/actions/runners/registration-token

# jobs:
#   my-jobname:
#     runs-on: ubuntu-latest
#     environment: test
#       SUPERSECRET: ${{ secrets.SuperSecret }}
#     steps:
#         run: |
#              gh api \
#              -H "Accept: application/vnd.github+json" \
#              /repos/OWNER/REPO/actions/secrets
   
#       - if: ${{ env.SUPERSECRET != '' }}
#         run: echo 'This step will only run if the secret has a value set.'
#       - if: ${{ env.SUPERSECRET == '' }}
#         run: echo 'This step will only run if the secret does not have a value set.'